main:
  steps:
    - executing_logger:
        steps:
          - call_logger_service:
              call: http.post
              args:
                url: https://dev-logging-service-ku3ghyogsq-el.a.run.app/execute
                auth:
                  type: OIDC
                body: {}
              result: logger_response
              
    - return_multiple_response_values:
        return:
          msg: $${logger_response.body.msg}
          status: $${logger_response.body.status}