name: CI Build Docker Image

on:
  pull_request:
    branches:
      - main
      - dev

    paths:
      - "framework/Dockerfile"
      - "framework/.dockerignore"

  workflow_dispatch:

defaults:
  run:
    working-directory: ./framework

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: framework:testing
          outputs: type=docker,dest=/tmp/framework.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/framework.tar
