name: CI ORCHESTRATOR RUN

defaults:
  run:
    working-directory: ./framework/

permissions:
  id-token: write
  contents: read

####################### Triggers ###############################

on:
  push:
    branches:
      - main
      - dev

    paths:
      - framework/elt_system
      - framework/metadata_system
      - framework/orchestrator

  pull_request:
    branches:
      - main
      - dev

    paths:
      - framework/elt_system
      - framework/metadata_system
      - framework/orchestrator

  workflow_dispatch:

######################## Jobs #######################################

jobs:

######################## Build #######################################

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "projects/144449440045/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: "github-workflows@instant-medium-491107-t6.iam.gserviceaccount.com"

      - name: Set up python 3.12.3
        uses: actions/setup-python@v6
        with:
          python-version: "3.12.3"

      - name: Setup Dependencies & Validate
        run: |
          echo "=== Step Start ==="
          python -m ensurepip --default-pip
          pip install --no-cache-dir -r requirements.txt
          echo "=== Broken Requirements Check ==="
          pip check
          echo "=== Step End ==="

      - name: Build Image
        run: |
          echo "=== Step Start ==="
          echo "=== Image Build ==="
          docker build -t framework:latest .
          echo "=== Image List ==="
          docker image ls
          echo "=== Step End ==="

      - name: Run Code
        run: |
          echo "=== Step Start ==="
          echo "ENV: $ENV"
          echo "=== Code Run Start ==="
          python -u -m orchestrator.orchestrator.main
          echo "=== Code Run End ==="
          echo "=== Step End ==="
        env:
          DB_URL: ${{ secrets.DB_URL }}
          ENV: ${{ vars.ENV }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

######################## Test #######################################

  test:
    needs: build
    runs-on:
      ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Up python 3.12.3
        uses: actions/setup-python@v6
        with:
          python-version: "3.12.3"

      - name: Setup Dependencies & Validate
        run: |
          echo "=== Step Start ==="
          python -m ensurepip --default-pip
          pip install --no-cache-dir -r dev-requirements.txt
          echo "=== Broken Requirements Check ==="
          pip check
          echo "=== Step End ==="

      - name: ruff Tests
        run: |
          echo "=== Step Start ==="
          echo "=== ruff check ==="
          ruff check elt_system/
          ruff check metadata_system/
          ruff check orchestrator/
          echo "=== ruff format ==="
          ruff format --check elt_system/
          ruff format --check metadata_system/
          ruff format --check orchestrator/
          echo "=== Step End ==="